version: '3.5'

x-services-volume:
  &dev-volume
  type: bind
  source: ./develop
  target: /develop
 
services:
    # mysql 8.4
    mysql-database:
        # image name
        image: mysql:8.4
        # Password and user name of mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASS: 'user'
        # Which port should be exposed
        ports:
            - 3306:3306
        container_name: mysql-database
        volumes:
            # Save the data in named "Volumes" of Docker
            - db-store:/var/lib/mysql
            # Or use the local file
            # - ./docker_db_data/mysql:/var/lib/mysql
            # Where to save the mysql's log
            - ./logs:/var/log/mysql:z
            # Where to load the my.cnf
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:z
        # Which network this container belongs to.
        networks:
            - app_net
    nginx:
        # image name
        image: nginx:1.29-alpine
        # Which port should be exposed
        ports:
        - 8080:8080
        volumes:
        # Where to find the files to serve
        - *dev-volume
        # Where to save nginx logs.
        - ./logs:/var/log/nginx
        # Where to load default.conf.
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: nginx
        # Which network this container belongs to.
        networks:
            - app_net
networks:
    # Containers in same network can access each other by using its container name as host name
    app_net:
        driver: "bridge"
volumes:
    db-store:
